# Generated by Django 5.2.17 on 2026-09-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_slug_alter_post_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(max_length=1000),
        ),
    ]
