# Generated by Django 5.2.17 on 2026-10-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_blogcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(max_length=1000000),
        ),
    ]
