# Generated by Django 5.2.17 on 2026-09-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=15)),
                ("content", models.TextField(max_length=200)),
            ],
        ),
    ]
