# Generated by Django 5.2.17 on 2026-09-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_contact_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
