# Generated by Django 5.2.17 on 2026-09-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="content",
            field=models.TextField(max_length=1000),
        ),
    ]
